### ISSUE TITLE
Parsing fails

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/nomad-parser-vasp#1]
I have a few cases which fail to parse with the latest git. This is not my calculation however, so I have actually no idea what is special about this specific 
[vasprun.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6207376/vasprun.zip)
case.

```
"root":{
"errors":string"parser failed with exception"
"event":string"task failed"
"task":string"parsing"
"proc":string"Calc"
"process":string"process_calc"
"tasks_status":string"FAILURE"
"error":string"invalid literal for int() with base 10: '32537************'"
"parser":string"parsers/vasp"
"step":string"parsers/vasp"
"logger":string"nomad.processing"
"exception":string"Traceback (most recent call last): File "/app/nomad/processing/data.py", line 460, in parsing self._parser_results, logger=logger) File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 1142, in parse self.parse_method() File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 903, in parse_method incar_parameters = self.parser.get_incar() File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 334, in get_incar incar.update(self._get_key_values('incar/v')) File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 312, in _get_key_values value = convert(value, dtype) File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 284, in convert return [convert(v, dtype) for v in val] File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 284, in <listcomp> return [convert(v, dtype) for v in val] File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 286, in convert return dtype(val) ValueError: invalid literal for int() with base 10: '32537************'"
"timestamp":string"2021-03-25 17:37.29"
"level":string"ERROR"
}

Traceback (most recent call last):
  File "/app/nomad/processing/data.py", line 460, in parsing
    self._parser_results, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 1142, in parse
    self.parse_method()
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 903, in parse_method
    incar_parameters = self.parser.get_incar()
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 334, in get_incar
    incar.update(self._get_key_values('incar/v'))
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 312, in _get_key_values
    value = convert(value, dtype)
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 284, in convert
    return [convert(v, dtype) for v in val]
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 284, in <listcomp>
    return [convert(v, dtype) for v in val]
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 286, in convert
    return dtype(val)
ValueError: invalid literal for int() with base 10: '32537************'
```

vasprun.xml attached

**Comment by ondracka** [comment]
This is the relevant part of the INCAR

`LDAUL = 36*2 72*1 108*1`

why is the xml so strange I have no idea: 

`<v type="int" name="LDAUL">
2 2 2 32537************ 82 0 48 0 49 0 1 2 2 3 3 3 4 4 4****** 49 0 0 0 1 0 1 2 0 1 3 0 33 0 36 72 108 0 0 0 33 0****** 8270****** 32537 0 0 33 0 0****** 0****** 0****** 33 0 0 0 0 0 0 0 33 0************************************ 33 0 0****** 0****** 0****** 1521 0****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1 ****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1 ****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1****** -1 ****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0 ****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0 ****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0 ****** 0****** 0****** 0****** 0****** 0****** 0****** 0****** 0
</v>`

**Comment by markus1978** [comment]
Thanks for the report. The XML looks strange, but the parser should handle it more gracefully.

**Comment by markus1978** [comment]
@ladinesa please take it from here. Ideally, you would introduce a general mechanism that handles exceptions while converting quantities and turns them into warnings.

In this specific instance, maybe the XML has a meaning, maybe its vasp problem. However, falling back to the INCAR is probably overkill.

**Comment by markus1978** [comment]
There is a new release, the docker image tag stable (`gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:stable`) points towards it. The parser in this release should have  the fix.

**Comment by ondracka** [comment]
Confirming fixed
