### ISSUE TITLE
Low performance of XML parsing due to findall

### ISSUE THREAD

**Issue by markus1978** [nomad-coe/nomad-parser-vasp#2]
The overall performance of the XML parser is not ideal. This is probably due to the overuse of XPath and `PathElement.findall`. I agree that this provides a nice interface and understandable code, but it comes at a cost. 

When I profile the parsing of a larger XML file it spends 70% of its time in `findall`. I am convinced this can be reduced to near zero with a traditional XML-tree traversal implementation. Another disadvantage of `findall` is that you need to create calculation sub-parsers just to keep `findall` under control. This part of the parser is hard to understand and produces quite a bit of code that would otherwise be unnecessary. 

When I take the old parser as a benchmark the runtime is 9s vs 15s. Where about 5s is just parser startup. So more like 4s vs 10s. 

This is the example, I am using: [vasprun.xml.relax1.xz.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6210136/vasprun.xml.relax1.xz.zip). Here is the profile running it with cProfile: 
[vasp.profile.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6210179/vasp.profile.zip). You can watch it with a tool like [SnakeViz](https://jiffyclub.github.io/snakeviz/).

@ladinesa Please consider to scrap the `findall` approach and think about refactoring the parser using a normal tree traversal.

**Comment by markus1978** [comment]
@ondracka This should addresses the hunch you had about the VASP parser performance.

**Comment by markus1978** [comment]
There is a new release, the docker image tag stable (`gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:stable`) points towards it. The parser in this release should have  the fix.

**Comment by ondracka** [comment]
Confirming, parsing is much faster now. This bug can be closed.
