### ISSUE TITLE
Workflow is detected as "geometry optimization" even when NSW = 0

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/nomad-parser-vasp#5]
When the number of ionic steps is 0, there is no optimization going on.

**Comment by markus1978** [comment]
@ladinesa, please have a loot at this. Either provide a fix or an explanation if this is intentional.

**Comment by ladinesa** [comment]
I only introduced the 'single_point' workflow a few days ago and have yet to implement the change across all parsers. As it stands, single point calculations are geometry optimizations with type static. I will make the change this week.

**Comment by ondracka** [comment]
OK, I see. I got confused, because the geometry_optimization_type description doesn't actually mention the "static". It says: "The type of geometry optimization can either be ionic, cell_shape, cell_volume." But there is probably no point in fixing this description if 'single_point' workflow will be introduced soon. I think this will be more intuitive anyway.

**Comment by ladinesa** [comment]
Addressed in v0.10.2. I will close this now.
