### ISSUE TITLE
VASP calculation not detected

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/nomad-parser-vasp#6]
The attached zip file has one selected VASP calculation with complete OUTCAR (as far as I can say), but it is not detected and nomad fails at processing with "No calculations found". Is this some problem with the calculation itself (I have a whole bunch of similar ones from one user) or a parser (mainfile detection) bug?
[8.9_0.6eV0.96.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6349064/8.9_0.6eV0.96.zip)

**Comment by markus1978** [comment]
@ladinesa Please have a look at this.

**Comment by ondracka** [comment]
The issue seems to be with the mainfile matching indeed i.e., the first line in my OUTCAR is:
` vasp.5.4.4.18Apr17-6-g9f103f2a35 (build Sep 11 2017 19:21:43) complex`

the current relevant part of mainfile_contents_re:
`?|^\svasp[\.\d]+\s*\w+\s*\(build')`
the issue is that the \w fails to match the dash, something like 

`?|^\svasp[\.\d]+\s*[\w-]+\s*\(build')`
could maybe work?

**Comment by ondracka** [comment]
My regex skills are failing me. \w in character class [] doesn't work as I thought it does,
`?|^\svasp[\.\d]+\s*\S+\s*\(build')`
works obviously, but might be too general?

**Comment by markus1978** [comment]
I think it is specific enough. It still has `vasp`, a version number, and `build` in it. Everything in one line. That is pretty unlikely to have it in other files.

**Comment by ladinesa** [comment]
Sorry for jumping in too late. Should I include a fix in the next commit or will you @ondracka will do it?

**Comment by ondracka** [comment]
@ladinesa please do it. Thanks.

**Comment by ondracka** [comment]
Actually hold the fix yet, I rebuilded my local image with the fix, but it still doesn't work, I need to do more testing.

**Comment by ladinesa** [comment]
@ondracka the current fix seems to work. I am closing this now.

**Comment by ondracka** [comment]
Confirming fixed
