### ISSUE TITLE
Another parsing failure: "TypeError: unsupported operand type(s) for +: 'int' and 'str'"

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/nomad-parser-vasp#8]
Another failure in what looks like a reasonable OUTCAR

[OUTCAR.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6353686/OUTCAR.zip)

```
Traceback (most recent call last):
  File "/app/nomad/processing/data.py", line 460, in parsing
    self._parser_results, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 1328, in parse
    self.parse_method()
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 1109, in parse_method
    atomtypes = self.parser.atom_info.get('atomtypes', {})
  File "/usr/local/lib/python3.7/site-packages/vaspparser/vasp_parser.py", line 432, in atom_info
    self._atom_info['n_atoms'] = sum(ions)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by markus1978** [comment]
@ladinesa please have a look at this.

**Comment by ladinesa** [comment]
I cannot reproduce the error on my machine. However, I put a safeguard which may work.

**Comment by ondracka** [comment]
Thanks, it no longer crash with the patch. Why it gave problems I have no idea though. My settings was just v10.2 with the yesterday's VASP parser fix and two other patches on top (both of which just changed the webpage wording to be more relevant for our oasis) and than I just do "docker build ."

BTW can you please check how many scf iterations you get when parsing this OUTCAR? There are 10 in the file but there is just first one parsed in the archive (I checked this also with the upstream nomad). Should I open a new bug about this or can we track it here as well?

**Comment by ladinesa** [comment]
I also get one. I will put up an immediate fix.

**Comment by ladinesa** [comment]
I just checked the processed calculations in the nomad database and the former problem also occurs on a calculation. It must be the behavior of a string operation but I am not certain. The latter issue should be addressed now with the latest commit.

**Comment by ondracka** [comment]
Confirming fixed
